benchmarks_dir: benchmarks/

outputs_dir: artifacts/

openai_models:
  - gpt-4o-mini

ollama_models:
  - llama3:8b
  - mistral:7b
  - gpt-oss:20b
  - qwen3:8b
  - deepseek-r1:8b
  - phi4-mini-reasoning
  - phi4-reasoning
  - llama3.1:8b
  - qwen2-math:7b
  - mightykatun/qwen2.5-math:7b

vllm_models:
  - meta-llama/Llama-3.1-8B-Instruct
  - meta-llama/Llama-3.1-8B

agents:
  - plan_react_agent
  - cot_plan_react_agent
  - baseline_react_agent
  - simple_planning_agent