embedding_model: sentence-transformers/all-mpnet-base-v2

table: rag_chunks

index: rag_chunks_embedding_idx
index_lists: 100

rag_text_files:
  - data/processed/openstax/university-physics-volume-1.collection.txt

max_chunk_tokens: 384
max_merge_tokens: 512
tokens_overlap: 128

retrieve_top_k: 4
